context:
  version: "25.4.2"

package:
  name: vpl-gpu-rt
  version: ${{ version }}

source:
  url: https://github.com/intel/vpl-gpu-rt/archive/refs/tags/intel-onevpl-${{ version }}.tar.gz
  sha256: c41eb0f090fc6226199774d3dbfbd072deac8249007551c9b013370ad3af0b79

build:
  skip:
    - win
    - osx
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - libva
    - libvpl
    - intel-media-driver
  run_exports:
    - ${{ pin_subpackage('vpl-gpu-rt', upper_bound='x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libmfx-gen.so
      - test -f ${PREFIX}/lib/libmfx-gen/enctools.so

about:
  homepage: https://github.com/intel/vpl-gpu-rt
  summary: 'Intel® Video Processing Library (Intel® VPL) GPU Runtime'
  description: |
    Intel® Video Processing Library (Intel® VPL) GPU Runtime is a Runtime
    implementation of Intel® VPL API for Intel Gen GPUs. Runtime provides
    access to hardware-accelerated video decode, encode and filtering.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
